### ISSUE TITLE
Growl notifications not being received

### ISSUE THREAD

**Issue by jonahx** [guard/guard-minitest#126]
Growl notification don't currently work (at least not for me on OS X).

Adding `require 'guard'` to the first line of this file: guard-minitest-2.4.3/lib/guard/minitest/notifier.rb

fixes the issue for me.

More details here: http://stackoverflow.com/questions/28291066/guard-not-sending-gntp-notifications-to-growl

**Comment by e2** [comment]
Thanks for reporting this

> Adding require 'guard' to the first line of this file: guard-minitest-2.4.3/lib/guard/minitest/notifier.rb

That's definitely not the right fix. If minitest is correctly run using bundler, it shouldn't make a difference (since bundler requires 'guard' anyway).

Could you provide the output when running tests when using the '-d' option for guard? (`bundle exec guard -d`)? That should show the command line for running minitest - and running it outside guard reproduce the same error.

Could you create a repo reproducing the problem? If I can reproduce it myself, I could see what's going on.

**Comment by jonahx** [comment]
Thanks for the quick reply.  

I figured the `require 'guard'` was a hacky fix, but at least it's working in the meantime.  Below is the output you requested (I removed the `require 'guard'` before running this).

I'm happy to help more, but I'm not sure what you mean by a repo reproducing the problem.  I encounter the problem anytime I use guard-minitest on my machine.  It's just a problem of growl not receiving the notifications.  There's nothing code specific going on.  Please clarify if I'm misunderstanding.  Thanks.

```
$ bundle exec guard -d
14:25:54 - DEBUG - Notiffany is using GNTP to send notifications.
14:25:54 - DEBUG - Command execution: hash stty
14:25:54 - DEBUG - Guard starts all plugins
14:25:54 - DEBUG - Hook :start_begin executed for Guard::Minitest
14:25:54 - INFO - Guard::Minitest 2.4.3 is running, with Minitest::Unit 5.5.1!
14:25:54 - INFO - Running: all tests
14:25:54 - DEBUG - Running: bundle exec ruby -I"test" -I"spec" -r bundler/setup -r minitest/autorun -r ./spec/test_helper.rb -r ./spec/beacons_app_spec.rb -e "" --
14:25:54 - DEBUG - Command execution: bundle exec ruby -I"test" -I"spec" -r bundler/setup -r minitest/autorun -r ./spec/test_helper.rb -r ./spec/beacons_app_spec.rb -e "" --

# Running tests with run options --seed 4934:

TEST
.

Finished tests in 0.014505s, 68.9417 tests/s, 206.8252 assertions/s.

1 tests, 3 assertions, 0 failures, 0 errors, 0 skips
1 tests
3 assertions, 0 failures, 0 errors

68.56 tests/s, 205.68 assertions/s

Finished in 0.0146 seconds
14:25:55 - DEBUG - Hook :start_end executed for Guard::Minitest
14:25:55 - INFO - Guard is now watching at '/Users/jg/Dropbox/sinatra/dash/beacons'
14:25:55 - DEBUG - Start interactor
14:25:55 - DEBUG - Command execution: stty -g 2>/dev/null
```

**Comment by e2** [comment]
Fixed in v2.4.4

Thanks for reporting this!

**Comment by jonahx** [comment]
Thank you for fixing so fast!

**Comment by kryptokommunist** [comment]
This fix unfortunately gives me the following error using Ruby on Rails (Which doesn't show up with guard-mintest 2.4.3):

Running ```bundle exec rake test``` produces:

```/Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- guard (LoadError)
	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/guard-minitest-2.4.4/lib/minitest/guard_minitest_plugin.rb:4:in `<top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/minitest-5.5.1/lib/minitest.rb:91:in `block in load_plugins'
	from /Library/Ruby/Gems/2.0.0/gems/minitest-5.5.1/lib/minitest.rb:85:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/minitest-5.5.1/lib/minitest.rb:85:in `load_plugins'
	from /Library/Ruby/Gems/2.0.0/gems/minitest-5.5.1/lib/minitest.rb:114:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/minitest-5.5.1/lib/minitest.rb:56:in `block in autorun'```

I'm just a noob, but it seems like  ```require 'guard'``` broke it, maybe it's even a problem with Rails and i should report it there?

**Comment by e2** [comment]
@kryptokommunist - make sure you are explicitly using `gem 'guard'` in your `Gemfile`, because I can't add `guard` as a dependency anywhere (guard plugins have to be able to work without guard in some cases).

If you still get the problem - create a small repo to reproduce the issue (the issue can be complex, but if you prepare a repo and I can reproduce it, I'll probably fix it fast).

> I'm just a noob

I disagree. minitest/guard-minitest is a nightmare compared to rspec/guard-rspec. (I avoid minitest like the plague, and guard-minitest continue to cause all kinds challenges making life difficult for me and everyone else - mostly because: 1) it's used for testing guard plugins and 2) because of the minitest plugin loading mechanism).

P.S. Nice to see a "Princess Mononoke" avatar - brings back good memories.

**Comment by kryptokommunist** [comment]
@e2 You nailed it, that solved the issue. I should have thought of that, but kinda got intimidated by this monstrous error message...

P.S.: "Princess Mononoke" is one of those movies one should watch at least once every two years. Btw. i can highly recommend "Nausicaä of the Valley of the Wind" if you didn't already watch it!

**Comment by e2** [comment]
@kryptokommunist - I fixed the README for now, but the best fix would be: https://github.com/guard/guard/issues/713 (I'll probably need to do it at some point).
